name: Build and Publish

on:
  push:
    branches:
      - '*'
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整提交历史

      - name: Set up Zulu 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Get current date
        id: get_date
        run: echo "DATE=$(TZ=Asia/Shanghai date +'%y%m%d')" >> $GITHUB_ENV

      - name: Get Git SHA
        id: get_sha
        run: echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Set VERSION environment variable
        run: |
          ORIGINAL_VERSION=$(grep "mod_version=" gradle.properties | cut -d ' ' -f2 | sed 's/[^0-9.]//g')
          echo "Setting VERSION to ${ORIGINAL_VERSION}-${{ env.DATE }}-${{ env.SHA }}"
          echo "VERSION=${ORIGINAL_VERSION}-${{ env.DATE }}-${{ env.SHA }}" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          git fetch --tags
          if git show-ref --tags --quiet refs/tags/${{ env.VERSION }}; then
            echo "Tag exists"
            echo "SKIP_BUILD=true" >> $GITHUB_ENV
          else
            echo "Tag does not exist"
            echo "SKIP_BUILD=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if commit message contains [skip] and if branch is master
        id: check_skip
        if: env.SKIP_BUILD == 'false'
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MESSAGE" == "[ci]"* ]]; then
            echo "SKIP_UPLOAD=false" >> $GITHUB_ENV
          else
            echo "SKIP_UPLOAD=true" >> $GITHUB_ENV
          fi

      - name: Update version in gradle.properties
        if: env.SKIP_BUILD == 'false'
        run: |
          sed -i "s/\(mod_version= \).*/\1'${{ env.VERSION }}'/" gradle.properties

      - name: Build with Gradle
        if: env.SKIP_BUILD == 'false'
        run: ./gradlew build

      - name: Rename JAR file
        if: env.SKIP_BUILD == 'false'
        id: rename_file
        run: |
          TARGET_JAR="CombatDepot-${{ env.VERSION }}.jar"
          SOURCE_JAR=$(find build/libs -name "*.jar" -print -quit)
          echo "FINAL_JAR_NAME=CombatDepot-${{ env.VERSION }}" >> $GITHUB_ENV
          mv "${SOURCE_JAR}" "${TARGET_JAR}"

      - name: Upload Artifact
        uses: "actions/upload-artifact@v4"
        with:
          name: ${{ env.FINAL_JAR_NAME }}
          path: ${{ env.FINAL_JAR_NAME }}.jar

      - name: Collect build info
        if: env.SKIP_BUILD == 'false'
        run: |
          echo "JAVA_VERSION=$(java -version 2>&1 | head -n 1 | sed 's/"//g')" >> $GITHUB_ENV
          echo "GRADLE_VERSION=$(./gradlew --version | grep Gradle | awk '{print $2}')" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Create Pre-Release and Upload JAR file
        if: env.SKIP_UPLOAD == 'false' && env.SKIP_BUILD == 'false'
        uses: ncipollo/release-action@v1.15.0
        with:
          tag: ${{ env.VERSION }}
          name: "CI Build - ${{ env.VERSION }}"
          body: |
            ## 注意事项
            此预发布版本由 GitHub Action 自动构建。
            
            请注意，此版本为测试版，并不代表最终版本。
            
            ---
            
            ## 构建信息
            | 属性          | 值                          |
            | ------------- | -------------------------- |
            | 版本号        | `${{ env.VERSION }}`        |
            | Java 版本     | `${{ env.JAVA_VERSION }}`   |
            | Gradle 版本   | `${{ env.GRADLE_VERSION }}` |
            | 构建时间      | `${{ env.BUILD_TIME }}`     |
            
            ## 触发信息
            - 触发方式: `${{ github.event_name }}`
            - 触发分支: `${{ github.ref }}`
            - 执行记录: [运行 #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - 操作账号: `${{ github.actor }}`
            
            ## 提交信息
            ```text
            SHA:    ${{ github.sha }}
            作者:    ${{ github.event.head_commit.author.name || 'N/A' }}
            时间:    ${{ github.event.head_commit.timestamp || env.BUILD_TIME }}
            消息:    ${{ github.event.head_commit.message || 'No commit message' }}
            ```

          draft: false
          prerelease: true
          makeLatest: true
          generateReleaseNotes: true
          artifacts: ${{ env.FINAL_JAR_NAME }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}
